"""
Chinabot_countries.py - 全球197个国家及汇率数据
"""
COUNTRIES = [
    # ===== 亚洲 =====
    {"name":"中国","aliases":["China","CN"],"currency":"CNY","currency_name":"人民币","usd_rate_range":[7.1,7.3]},
    {"name":"日本","aliases":["Japan","JP"],"currency":"JPY","currency_name":"日元","usd_rate_range":[145,155]},
    {"name":"韩国","aliases":["Korea","KR"],"currency":"KRW","currency_name":"韩元","usd_rate_range":[1300,1400]},
    {"name":"印度","aliases":["India","IN"],"currency":"INR","currency_name":"印度卢比","usd_rate_range":[82,85]},
    {"name":"印度尼西亚","aliases":["Indonesia","ID","印尼"],"currency":"IDR","currency_name":"印尼盾","usd_rate_range":[15500,16500]},
    {"name":"马来西亚","aliases":["Malaysia","MY"],"currency":"MYR","currency_name":"马来西亚林吉特","usd_rate_range":[4.3,4.8]},
    {"name":"菲律宾","aliases":["Philippines","PH"],"currency":"PHP","currency_name":"菲律宾比索","usd_rate_range":[55,59]},
    {"name":"新加坡","aliases":["Singapore","SG"],"currency":"SGD","currency_name":"新加坡元","usd_rate_range":[1.3,1.4]},
    {"name":"泰国","aliases":["Thailand","TH"],"currency":"THB","currency_name":"泰铢","usd_rate_range":[34,37]},
    {"name":"越南","aliases":["Vietnam","VN"],"currency":"VND","currency_name":"越南盾","usd_rate_range":[24500,25500]},
    {"name":"巴基斯坦","aliases":["Pakistan","PK","巴铁"],"currency":"PKR","currency_name":"巴基斯坦卢比","usd_rate_range":[275,290]},
    {"name":"孟加拉国","aliases":["Bangladesh","BD"],"currency":"BDT","currency_name":"孟加拉塔卡","usd_rate_range":[108,115]},
    {"name":"缅甸","aliases":["Myanmar","MM"],"currency":"MMK","currency_name":"缅甸缅元","usd_rate_range":[3000,3500]},
    {"name":"柬埔寨","aliases":["Cambodia","KH"],"currency":"KHR","currency_name":"柬埔寨瑞尔","usd_rate_range":[4000,4200]},
    {"name":"老挝","aliases":["Laos","LA"],"currency":"LAK","currency_name":"老挝基普","usd_rate_range":[21000,22000]},
    {"name":"尼泊尔","aliases":["Nepal","NP"],"currency":"NPR","currency_name":"尼泊尔卢比","usd_rate_range":[130,138]},
    {"name":"斯里兰卡","aliases":["Sri Lanka","LK"],"currency":"LKR","currency_name":"斯里兰卡卢比","usd_rate_range":[300,330]},
    {"name":"蒙古","aliases":["Mongolia","MN"],"currency":"MNT","currency_name":"蒙古图格里克","usd_rate_range":[3400,3500]},
    {"name":"朝鲜","aliases":["North Korea","KP"],"currency":"KPW","currency_name":"朝鲜元","usd_rate_range":[900,900]},
    {"name":"文莱","aliases":["Brunei","BN"],"currency":"BND","currency_name":"文莱元","usd_rate_range":[1.3,1.4]},
    {"name":"东帝汶","aliases":["Timor-Leste","TL"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"马尔代夫","aliases":["Maldives","MV"],"currency":"MVR","currency_name":"马尔代夫拉菲亚","usd_rate_range":[15.3,15.5]},
    {"name":"不丹","aliases":["Bhutan","BT"],"currency":"BTN","currency_name":"不丹努尔特鲁姆","usd_rate_range":[82,85]},
    {"name":"阿富汗","aliases":["Afghanistan","AF"],"currency":"AFN","currency_name":"阿富汗尼","usd_rate_range":[70,75]},
    {"name":"伊朗","aliases":["Iran","IR"],"currency":"IRR","currency_name":"伊朗里亚尔","usd_rate_range":[42000,43000]},
    {"name":"伊拉克","aliases":["Iraq","IQ"],"currency":"IQD","currency_name":"伊拉克第纳尔","usd_rate_range":[1300,1320]},
    {"name":"叙利亚","aliases":["Syria","SY"],"currency":"SYP","currency_name":"叙利亚镑","usd_rate_range":[13000,14000]},
    {"name":"约旦","aliases":["Jordan","JO"],"currency":"JOD","currency_name":"约旦第纳尔","usd_rate_range":[0.7,0.71]},
    {"name":"黎巴嫩","aliases":["Lebanon","LB"],"currency":"LBP","currency_name":"黎巴嫩镑","usd_rate_range":[89000,90000]},
    {"name":"以色列","aliases":["Israel","IL"],"currency":"ILS","currency_name":"以色列新谢克尔","usd_rate_range":[3.5,3.8]},
    {"name":"巴勒斯坦","aliases":["Palestine","PS"],"currency":"ILS","currency_name":"以色列新谢克尔","usd_rate_range":[3.5,3.8]},
    {"name":"沙特阿拉伯","aliases":["Saudi Arabia","SA"],"currency":"SAR","currency_name":"沙特里亚尔","usd_rate_range":[3.75,3.76]},
    {"name":"阿联酋","aliases":["UAE","AE","迪拜","Dubai"],"currency":"AED","currency_name":"阿联酋迪拉姆","usd_rate_range":[3.65,3.68]},
    {"name":"卡塔尔","aliases":["Qatar","QA"],"currency":"QAR","currency_name":"卡塔尔里亚尔","usd_rate_range":[3.64,3.65]},
    {"name":"科威特","aliases":["Kuwait","KW"],"currency":"KWD","currency_name":"科威特第纳尔","usd_rate_range":[0.3,0.31]},
    {"name":"巴林","aliases":["Bahrain","BH"],"currency":"BHD","currency_name":"巴林第纳尔","usd_rate_range":[0.376,0.378]},
    {"name":"阿曼","aliases":["Oman","OM"],"currency":"OMR","currency_name":"阿曼里亚尔","usd_rate_range":[0.38,0.39]},
    {"name":"也门","aliases":["Yemen","YE"],"currency":"YER","currency_name":"也门里亚尔","usd_rate_range":[250,250]},
    {"name":"土耳其","aliases":["Turkey","TR"],"currency":"TRY","currency_name":"土耳其里拉","usd_rate_range":[32,34]},
    {"name":"塞浦路斯","aliases":["Cyprus","CY"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"格鲁吉亚","aliases":["Georgia","GE"],"currency":"GEL","currency_name":"格鲁吉亚拉里","usd_rate_range":[2.6,2.8]},
    {"name":"亚美尼亚","aliases":["Armenia","AM"],"currency":"AMD","currency_name":"亚美尼亚德拉姆","usd_rate_range":[390,410]},
    {"name":"阿塞拜疆","aliases":["Azerbaijan","AZ"],"currency":"AZN","currency_name":"阿塞拜疆马纳特","usd_rate_range":[1.7,1.8]},
    {"name":"哈萨克斯坦","aliases":["Kazakhstan","KZ"],"currency":"KZT","currency_name":"哈萨克斯坦坚戈","usd_rate_range":[450,480]},
    {"name":"乌兹别克斯坦","aliases":["Uzbekistan","UZ"],"currency":"UZS","currency_name":"乌兹别克斯坦索姆","usd_rate_range":[12500,13000]},
    {"name":"土库曼斯坦","aliases":["Turkmenistan","TM"],"currency":"TMT","currency_name":"土库曼斯坦马纳特","usd_rate_range":[3.5,3.5]},
    {"name":"吉尔吉斯斯坦","aliases":["Kyrgyzstan","KG"],"currency":"KGS","currency_name":"吉尔吉斯斯坦索姆","usd_rate_range":[88,90]},
    {"name":"塔吉克斯坦","aliases":["Tajikistan","TJ"],"currency":"TJS","currency_name":"塔吉克斯坦索莫尼","usd_rate_range":[10.8,11.0]},

    # ===== 欧洲 =====
    {"name":"俄罗斯","aliases":["Russia","RU"],"currency":"RUB","currency_name":"俄罗斯卢布","usd_rate_range":[88,95]},
    {"name":"德国","aliases":["Germany","DE"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"法国","aliases":["France","FR"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"英国","aliases":["UK","GB"],"currency":"GBP","currency_name":"英镑","usd_rate_range":[0.78,0.81]},
    {"name":"意大利","aliases":["Italy","IT"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"西班牙","aliases":["Spain","ES"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"乌克兰","aliases":["Ukraine","UA"],"currency":"UAH","currency_name":"乌克兰格里夫纳","usd_rate_range":[38,41]},
    {"name":"波兰","aliases":["Poland","PL"],"currency":"PLN","currency_name":"波兰兹罗提","usd_rate_range":[3.9,4.2]},
    {"name":"荷兰","aliases":["Netherlands","NL"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"比利时","aliases":["Belgium","BE"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"葡萄牙","aliases":["Portugal","PT"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"希腊","aliases":["Greece","GR"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"瑞典","aliases":["Sweden","SE"],"currency":"SEK","currency_name":"瑞典克朗","usd_rate_range":[10,11]},
    {"name":"挪威","aliases":["Norway","NO"],"currency":"NOK","currency_name":"挪威克朗","usd_rate_range":[10.5,11.5]},
    {"name":"丹麦","aliases":["Denmark","DK"],"currency":"DKK","currency_name":"丹麦克朗","usd_rate_range":[6.8,7.2]},
    {"name":"芬兰","aliases":["Finland","FI"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"瑞士","aliases":["Switzerland","CH"],"currency":"CHF","currency_name":"瑞士法郎","usd_rate_range":[0.88,0.91]},
    {"name":"奥地利","aliases":["Austria","AT"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"爱尔兰","aliases":["Ireland","IE"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"捷克","aliases":["Czech","CZ"],"currency":"CZK","currency_name":"捷克克朗","usd_rate_range":[22.5,23.5]},
    {"name":"匈牙利","aliases":["Hungary","HU"],"currency":"HUF","currency_name":"匈牙利福林","usd_rate_range":[350,380]},
    {"name":"罗马尼亚","aliases":["Romania","RO"],"currency":"RON","currency_name":"罗马尼亚列伊","usd_rate_range":[4.5,4.8]},
    {"name":"保加利亚","aliases":["Bulgaria","BG"],"currency":"BGN","currency_name":"保加利亚列弗","usd_rate_range":[1.78,1.85]},
    {"name":"塞尔维亚","aliases":["Serbia","RS"],"currency":"RSD","currency_name":"塞尔维亚第纳尔","usd_rate_range":[105,110]},
    {"name":"克罗地亚","aliases":["Croatia","HR"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"斯洛文尼亚","aliases":["Slovenia","SI"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"斯洛伐克","aliases":["Slovakia","SK"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"立陶宛","aliases":["Lithuania","LT"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"拉脱维亚","aliases":["Latvia","LV"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"爱沙尼亚","aliases":["Estonia","EE"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"白俄罗斯","aliases":["Belarus","BY"],"currency":"BYN","currency_name":"白俄罗斯卢布","usd_rate_range":[3.2,3.3]},
    {"name":"摩尔多瓦","aliases":["Moldova","MD"],"currency":"MDL","currency_name":"摩尔多瓦列伊","usd_rate_range":[17.5,18.5]},
    {"name":"波黑","aliases":["Bosnia","BA"],"currency":"BAM","currency_name":"波黑可马克","usd_rate_range":[1.78,1.85]},
    {"name":"北马其顿","aliases":["North Macedonia","MK"],"currency":"MKD","currency_name":"北马其顿第纳尔","usd_rate_range":[56,58]},
    {"name":"阿尔巴尼亚","aliases":["Albania","AL"],"currency":"ALL","currency_name":"阿尔巴尼亚列克","usd_rate_range":[93,98]},
    {"name":"冰岛","aliases":["Iceland","IS"],"currency":"ISK","currency_name":"冰岛克朗","usd_rate_range":[135,140]},
    {"name":"卢森堡","aliases":["Luxembourg","LU"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"马耳他","aliases":["Malta","MT"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"摩纳哥","aliases":["Monaco","MC"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"列支敦士登","aliases":["Liechtenstein","LI"],"currency":"CHF","currency_name":"瑞士法郎","usd_rate_range":[0.88,0.91]},
    {"name":"安道尔","aliases":["Andorra","AD"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"圣马力诺","aliases":["San Marino","SM"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},
    {"name":"梵蒂冈","aliases":["Vatican","VA"],"currency":"EUR","currency_name":"欧元","usd_rate_range":[0.91,0.95]},

    # ===== 非洲 =====
    {"name":"南非","aliases":["South Africa","ZA"],"currency":"ZAR","currency_name":"南非兰特","usd_rate_range":[18,20]},
    {"name":"埃及","aliases":["Egypt","EG"],"currency":"EGP","currency_name":"埃及镑","usd_rate_range":[47,50]},
    {"name":"尼日利亚","aliases":["Nigeria","NG","拉各斯"],"currency":"NGN","currency_name":"尼日利亚奈拉","usd_rate_range":[1500,1700]},
    {"name":"肯尼亚","aliases":["Kenya","KE"],"currency":"KES","currency_name":"肯尼亚先令","usd_rate_range":[125,135]},
    {"name":"坦桑尼亚","aliases":["坦桑","Tanzania","TZ"],"currency":"TZS","currency_name":"坦桑尼亚先令","usd_rate_range":[2500,2700]},
    {"name":"埃塞俄比亚","aliases":["Ethiopia","ET","埃塞"],"currency":"ETB","currency_name":"埃塞俄比亚比尔","usd_rate_range":[55,60]},
    {"name":"加纳","aliases":["Ghana","GH"],"currency":"GHS","currency_name":"加纳塞地","usd_rate_range":[12,15]},
    {"name":"摩洛哥","aliases":["Morocco","MA"],"currency":"MAD","currency_name":"摩洛哥迪拉姆","usd_rate_range":[9.8,10.5]},
    {"name":"乌干达","aliases":["Uganda","UG"],"currency":"UGX","currency_name":"乌干达先令","usd_rate_range":[3700,3900]},
    {"name":"卢旺达","aliases":["Rwanda","RW"],"currency":"RWF","currency_name":"卢旺达法郎","usd_rate_range":[1250,1350]},
    {"name":"喀麦隆","aliases":["Cameroon","CM"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"阿尔及利亚","aliases":["Algeria","DZ"],"currency":"DZD","currency_name":"阿尔及利亚第纳尔","usd_rate_range":[134,138]},
    {"name":"安哥拉","aliases":["Angola","AO"],"currency":"AOA","currency_name":"安哥拉宽扎","usd_rate_range":[830,870]},
    {"name":"突尼斯","aliases":["Tunisia","TN"],"currency":"TND","currency_name":"突尼斯第纳尔","usd_rate_range":[3.0,3.2]},
    {"name":"利比亚","aliases":["Libya","LY"],"currency":"LYD","currency_name":"利比亚第纳尔","usd_rate_range":[4.8,4.9]},
    {"name":"苏丹","aliases":["Sudan","SD"],"currency":"SDG","currency_name":"苏丹镑","usd_rate_range":[600,650]},
    {"name":"南苏丹","aliases":["South Sudan","SS"],"currency":"SSP","currency_name":"南苏丹镑","usd_rate_range":[1500,1600]},
    {"name":"刚果民主共和国","aliases":["DR Congo","CD","刚果金"],"currency":"CDF","currency_name":"刚果法郎","usd_rate_range":[2700,2800]},
    {"name":"刚果共和国","aliases":["Congo","CG","刚果布"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"科特迪瓦","aliases":["Ivory Coast","CI"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"塞内加尔","aliases":["Senegal","SN"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"马里","aliases":["Mali","ML"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"布基纳法索","aliases":["Burkina Faso","BF"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"马达加斯加","aliases":["Madagascar","MG"],"currency":"MGA","currency_name":"马达加斯加阿里亚里","usd_rate_range":[4400,4600]},
    {"name":"莫桑比克","aliases":["Mozambique","MZ"],"currency":"MZN","currency_name":"莫桑比克梅蒂卡尔","usd_rate_range":[63,65]},
    {"name":"津巴布韦","aliases":["Zimbabwe","ZW"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"赞比亚","aliases":["Zambia","ZM"],"currency":"ZMW","currency_name":"赞比亚克瓦查","usd_rate_range":[25,28]},
    {"name":"马拉维","aliases":["Malawi","MW"],"currency":"MWK","currency_name":"马拉维克瓦查","usd_rate_range":[1700,1750]},
    {"name":"博茨瓦纳","aliases":["Botswana","BW"],"currency":"BWP","currency_name":"博茨瓦纳普拉","usd_rate_range":[13,14]},
    {"name":"纳米比亚","aliases":["Namibia","NA"],"currency":"NAD","currency_name":"纳米比亚元","usd_rate_range":[18,20]},
    {"name":"毛里求斯","aliases":["Mauritius","MU"],"currency":"MUR","currency_name":"毛里求斯卢比","usd_rate_range":[44,47]},
    {"name":"塞舌尔","aliases":["Seychelles","SC"],"currency":"SCR","currency_name":"塞舌尔卢比","usd_rate_range":[13,14]},
    {"name":"吉布提","aliases":["Djibouti","DJ"],"currency":"DJF","currency_name":"吉布提法郎","usd_rate_range":[177,179]},
    {"name":"几内亚","aliases":["Guinea","GN"],"currency":"GNF","currency_name":"几内亚法郎","usd_rate_range":[8500,8700]},
    {"name":"塞拉利昂","aliases":["Sierra Leone","SL"],"currency":"SLL","currency_name":"塞拉利昂利昂","usd_rate_range":[22500,23000]},
    {"name":"利比里亚","aliases":["Liberia","LR"],"currency":"LRD","currency_name":"利比里亚元","usd_rate_range":[190,195]},
    {"name":"多哥","aliases":["Togo","TG"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"贝宁","aliases":["Benin","BJ"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"尼日尔","aliases":["Niger","NE"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"乍得","aliases":["Chad","TD"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"中非共和国","aliases":["Central African Republic","CF"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"加蓬","aliases":["Gabon","GA"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"赤道几内亚","aliases":["Equatorial Guinea","GQ"],"currency":"XAF","currency_name":"中非法郎","usd_rate_range":[600,630]},
    {"name":"毛里塔尼亚","aliases":["Mauritania","MR"],"currency":"MRU","currency_name":"毛里塔尼亚乌吉亚","usd_rate_range":[39,40]},
    {"name":"冈比亚","aliases":["Gambia","GM"],"currency":"GMD","currency_name":"冈比亚达拉西","usd_rate_range":[65,68]},
    {"name":"几内亚比绍","aliases":["Guinea-Bissau","GW"],"currency":"XOF","currency_name":"西非法郎","usd_rate_range":[600,630]},
    {"name":"布隆迪","aliases":["Burundi","BI"],"currency":"BIF","currency_name":"布隆迪法郎","usd_rate_range":[2850,2900]},
    {"name":"索马里","aliases":["Somalia","SO"],"currency":"SOS","currency_name":"索马里先令","usd_rate_range":[570,580]},
    {"name":"厄立特里亚","aliases":["Eritrea","ER"],"currency":"ERN","currency_name":"厄立特里亚纳克法","usd_rate_range":[15,15]},
    {"name":"斯威士兰","aliases":["Eswatini","SZ"],"currency":"SZL","currency_name":"斯威士兰里兰吉尼","usd_rate_range":[18,20]},
    {"name":"莱索托","aliases":["Lesotho","LS"],"currency":"LSL","currency_name":"莱索托洛蒂","usd_rate_range":[18,20]},
    {"name":"科摩罗","aliases":["Comoros","KM"],"currency":"KMF","currency_name":"科摩罗法郎","usd_rate_range":[450,470]},
    {"name":"佛得角","aliases":["Cape Verde","CV"],"currency":"CVE","currency_name":"佛得角埃斯库多","usd_rate_range":[100,105]},
    {"name":"圣多美和普林西比","aliases":["Sao Tome","ST"],"currency":"STN","currency_name":"圣多美多布拉","usd_rate_range":[22,23]},

    # ===== 北美洲 =====
    {"name":"美国","aliases":["USA","US"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"加拿大","aliases":["Canada","CA"],"currency":"CAD","currency_name":"加拿大元","usd_rate_range":[1.35,1.40]},
    {"name":"墨西哥","aliases":["Mexico","MX"],"currency":"MXN","currency_name":"墨西哥比索","usd_rate_range":[16.5,18]},
    {"name":"危地马拉","aliases":["Guatemala","GT"],"currency":"GTQ","currency_name":"危地马拉格查尔","usd_rate_range":[7.7,7.9]},
    {"name":"古巴","aliases":["Cuba","CU"],"currency":"CUP","currency_name":"古巴比索","usd_rate_range":[24,24]},
    {"name":"海地","aliases":["Haiti","HT"],"currency":"HTG","currency_name":"海地古德","usd_rate_range":[130,135]},
    {"name":"多米尼加","aliases":["Dominican Republic","DO"],"currency":"DOP","currency_name":"多米尼加比索","usd_rate_range":[58,60]},
    {"name":"洪都拉斯","aliases":["洪都","Honduras","HN"],"currency":"HNL","currency_name":"洪都拉斯伦皮拉","usd_rate_range":[24,25]},
    {"name":"尼加拉瓜","aliases":["Nicaragua","NI"],"currency":"NIO","currency_name":"尼加拉瓜科多巴","usd_rate_range":[36,37]},
    {"name":"哥斯达黎加","aliases":["Costa Rica","CR"],"currency":"CRC","currency_name":"哥斯达黎加科朗","usd_rate_range":[510,530]},
    {"name":"巴拿马","aliases":["Panama","PA"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"萨尔瓦多","aliases":["El Salvador","SV"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"伯利兹","aliases":["Belize","BZ"],"currency":"BZD","currency_name":"伯利兹元","usd_rate_range":[2.0,2.0]},
    {"name":"牙买加","aliases":["Jamaica","JM"],"currency":"JMD","currency_name":"牙买加元","usd_rate_range":[155,160]},
    {"name":"巴哈马","aliases":["Bahamas","BS"],"currency":"BSD","currency_name":"巴哈马元","usd_rate_range":[1,1]},
    {"name":"巴巴多斯","aliases":["Barbados","BB"],"currency":"BBD","currency_name":"巴巴多斯元","usd_rate_range":[2,2]},
    {"name":"特立尼达和多巴哥","aliases":["Trinidad and Tobago","TT"],"currency":"TTD","currency_name":"特立尼达多巴哥元","usd_rate_range":[6.7,6.8]},

    # ===== 南美洲 =====
    {"name":"巴西","aliases":["Brazil","BR"],"currency":"BRL","currency_name":"巴西雷亚尔","usd_rate_range":[5.0,5.5]},
    {"name":"阿根廷","aliases":["Argentina","AR"],"currency":"ARS","currency_name":"阿根廷比索","usd_rate_range":[850,950]},
    {"name":"哥伦比亚","aliases":["Colombia","CO"],"currency":"COP","currency_name":"哥伦比亚比索","usd_rate_range":[3800,4200]},
    {"name":"秘鲁","aliases":["Peru","PE"],"currency":"PEN","currency_name":"秘鲁索尔","usd_rate_range":[3.7,3.9]},
    {"name":"智利","aliases":["Chile","CL"],"currency":"CLP","currency_name":"智利比索","usd_rate_range":[920,980]},
    {"name":"委内瑞拉","aliases":["Venezuela","VE"],"currency":"VES","currency_name":"委内瑞拉玻利瓦尔","usd_rate_range":[36,40]},
    {"name":"厄瓜多尔","aliases":["Ecuador","EC"],"currency":"USD","currency_name":"美元","usd_rate_range":[1,1]},
    {"name":"玻利维亚","aliases":["Bolivia","BO"],"currency":"BOB","currency_name":"玻利维亚诺","usd_rate_range":[6.8,7.0]},
    {"name":"巴拉圭","aliases":["Paraguay","PY"],"currency":"PYG","currency_name":"巴拉圭瓜拉尼","usd_rate_range":[7400,7600]},
    {"name":"乌拉圭","aliases":["Uruguay","UY"],"currency":"UYU","currency_name":"乌拉圭比索","usd_rate_range":[38,41]},
    {"name":"圭亚那","aliases":["Guyana","GY"],"currency":"GYD","currency_name":"圭亚那元","usd_rate_range":[209,210]},
    {"name":"苏里南","aliases":["Suriname","SR"],"currency":"SRD","currency_name":"苏里南元","usd_rate_range":[36,38]},

    # ===== 大洋洲 =====
    {"name":"澳大利亚","aliases":["Australia","AU","澳洲"],"currency":"AUD","currency_name":"澳大利亚元","usd_rate_range":[1.48,1.55]},
    {"name":"新西兰","aliases":["New Zealand","NZ"],"currency":"NZD","currency_name":"新西兰元","usd_rate_range":[1.60,1.68]},
    {"name":"巴布亚新几内亚","aliases":["Papua New Guinea","PG"],"currency":"PGK","currency_name":"巴布亚新几内亚基那","usd_rate_range":[3.7,3.8]},
    {"name":"斐济","aliases":["Fiji","FJ"],"currency":"FJD","currency_name":"斐济元","usd_rate_range":[2.2,2.3]},
    {"name":"所罗门群岛","aliases":["Solomon Islands","SB"],"currency":"SBD","currency_name":"所罗门群岛元","usd_rate_range":[8.3,8.4]},
    {"name":"瓦努阿图","aliases":["Vanuatu","VU"],"currency":"VUV","currency_name":"瓦努阿图瓦图","usd_rate_range":[118,120]},
    {"name":"萨摩亚","aliases":["Samoa","WS"],"currency":"WST","currency_name":"萨摩亚塔拉","usd_rate_range":[2.7,2.8]},
    {"name":"汤加","aliases":["Tonga","TO"],"currency":"TOP","currency_name":"汤加潘加","usd_rate_range":[2.3,2.4]},
]

def get_all_countries():
    return COUNTRIES